import Config

# Configure your database
config :mayer, Mayer.Repo,
  username: "mayer_admin",
  password: "mayer_admin",
  hostname: "mysql",
  database: "mayer_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :mayer, Mayer.MongoRepo,
  hostname: "mongo",
  auth_source: "admin",
  username: "mayer_admin",
  password: "mayer_admin",
  database: "mayer_dev",
  pool_size: 10,
  timeout: 60_000,
  idle_interval: 10_000,
  queue_target: 5_000

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :mayer, MayerWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "mkdQGy0/w6i9mdD3rJnFETAA2NJthf8G/jKjAsUokLeBsBK1R6JrDB1jPJ5khuyO",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
config :swoosh, serve_mailbox: true
config :swoosh, serve_mailbox: true, preview_port: 4001
