export const Routes = {
  Introduction: { path: "/"},
  Project: { path: "/project" },
  Schema: { path: "/schema" },
  SchemaDetail: { path: "/schema/:schemaId" },
  Dataset: { path: "/dataset" },
  MockAPI: { path: "/mock-api" },
  Signin: { path: "/sign-in" },
  Signup: { path: "/sign-up" },
  ForgotPassword: { path: "/forgot-password" },
  NotFound: { path: "/404" },
  ServerError: { path: "/500" },
  ResetPassword: { path: "/reset-password" },
  Account: { path: "/account" },
};
